name       : n1
version    : 0.4.10
release    : 3
source     :
    - https://github.com/nylas/N1/releases/download/0.4.10/N1-0.4.10.deb : 2f83bc7100c2378602d0859b7ad6d3244398afe9ee0ee737116cedad7c48290d
license    : GPL-3.0
summary    : N1 Email Client
description: |
    An extensible mail client built on the modern web. 
rundeps  :
    - libgtk-2
    - libgnome-keyring
    - desktop-file-utils
    - python
    - gconf
    - nodejs
    - libnotify
    - libxtst
    - libnss
    - alsa-lib
extract    : no
setup      : |
    ar x $sources/N1-${version}.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
