name       : n1
version    : 0.4.5
release    : 2
source     :
    - https://github.com/nylas/N1/releases/download/0.4.5/N1-0.4.5.deb : 892afe593631ea485fa327e5db4fc8bec316574edd00002fab0758107f835c74
license    : GPL-3.0
summary    : N1 Email Client
description: |
    An extensible mail client built on the modern web. 
rundeps  :
    - libgtk-2
    - libgnome-keyring
    - desktop-file-utils
    - python
    - gconf
    - nodejs
    - libnotify
    - libxtst
    - libnss
    - alsa-lib
extract    : no
setup      : |
    ar x $sources/N1-${version}.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
