name       : n1
version    : 0.4.59
release    : 11
source     :
    - https://github.com/nylas/N1/releases/download/0.4.59/N1-0.4.59.deb : 661127d9487406038f37b0f79f34eced613249326290b03cf1f22a20c0feeffc
license    : GPL-3.0
summary    : N1 Email Client
component  : network.mail
description: An extensible mail client built on the modern web.
rundeps    :
    - alsa-lib
    - desktop-file-utils
    - gconf
    - libgnome-keyring
    - libgtk-2
    - libnotify
    - libnss
    - libxtst
    - nodejs
    - python
extract    : no
setup      : |
    ar x $sources/N1-${version}.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
    sed -i 's/Categories=GNOME;GTK;Email;Utility;Development;/Categories=Application;Network;Email;/g' %installroot%/usr/share/applications/nylas.desktop
