name       : n1
version    : 0.4.47
release    : 9
source     :
    - https://github.com/nylas/N1/releases/download/0.4.47/N1-0.4.47.deb : d9aeb394718413773da6a0f09a953174d60c853084a60747012aaa40f0471089
license    : GPL-3.0
summary    : N1 Email Client
component  : network.mail
description: "An extensible mail client built on the modern web. \n"
rundeps    :
    - libgtk-2
    - libgnome-keyring
    - desktop-file-utils
    - python
    - gconf
    - nodejs
    - libnotify
    - libxtst
    - libnss
    - alsa-lib
extract    : no
setup      : |
    ar x $sources/N1-${version}.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
    sed -i 's/Categories=GNOME;GTK;Email;Utility;Development;/Categories=Application;Network;Email;/g' %installroot%/usr/share/applications/nylas.desktop
