name       : n1
version    : 0.4.45
release    : 8
source     :
    - https://github.com/nylas/N1/releases/download/0.4.45/N1-0.4.45.deb : 50be9402670bf21df69dc5c294a745a07324e5248aafe03fa97228113e0796f8
license    : GPL-3.0
summary    : N1 Email Client
component  : network.mail
description: "An extensible mail client built on the modern web. \n"
rundeps    :
    - libgtk-2
    - libgnome-keyring
    - desktop-file-utils
    - python
    - gconf
    - nodejs
    - libnotify
    - libxtst
    - libnss
    - alsa-lib
extract    : no
setup      : |
    ar x $sources/N1-${version}.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
    sed -i 's/Categories=GNOME;GTK;Email;Utility;Development;/Categories=Application;Network;Email;/g' %installroot%/usr/share/applications/nylas.desktop
