name       : n1
version    : 0.4.14
release    : 4
source     :
    - https://github.com/nylas/N1/releases/download/0.4.14/N1-0.4.14.deb : 8496e58ba8d439ac4cd797d7df742b3ce40b82bbca58ace8340b0a1cbe8ee66f
license    : GPL-3.0
summary    : N1 Email Client
description: |
    An extensible mail client built on the modern web. 
rundeps  :
    - libgtk-2
    - libgnome-keyring
    - desktop-file-utils
    - python
    - gconf
    - nodejs
    - libnotify
    - libxtst
    - libnss
    - alsa-lib
extract    : no
setup      : |
    ar x $sources/N1-${version}.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
    sed -i 's/Categories=GNOME;GTK;Email;Utility;Development;/Categories=Application;Network;Email;/g' %installroot%/usr/share/applications/nylas.desktop
